In [14]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
import re

nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Yavanash\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [2]:
df = pd.read_csv("news_summary.csv", encoding="latin-1")
df.head(5)

,author,date,headlines,read_more,text,ctext
0,Chhavi Tyagi,"03 Aug 2017,Thursday",Daman & Diu revokes mandatory Rakshabandhan in...,http://www.hindustantimes.com/india-news/raksh...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday ...
1,Daisy Mowke,"03 Aug 2017,Thursday",Malaika slams user who trolled her for 'divorc...,http://www.hindustantimes.com/bollywood/malaik...,Malaika Arora slammed an Instagram user who tr...,"From her special numbers to TV?appearances, Bo..."
2,Arshiya Chopra,"03 Aug 2017,Thursday",'Virgin' now corrected to 'Unmarried' in IGIMS...,http://www.hindustantimes.com/patna/bihar-igim...,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Science...
3,Sumedha Sehra,"03 Aug 2017,Thursday",Aaj aapne pakad liya: LeT man Dujana before be...,http://indiatoday.intoday.in/story/abu-dujana-...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...
4,Aarushi Maheshwari,"03 Aug 2017,Thursday",Hotel staff to get training to spot signs of s...,http://indiatoday.intoday.in/story/sex-traffic...,Hotels in Maharashtra will train their staff t...,Hotels in Mumbai and other Indian cities are t...

In [3]:
df = df.drop(columns=["author", "date", "read_more"])

In [4]:
df["article"] = df["headlines"] + " " + df["ctext"]

In [5]:
df.head()

,headlines,text,ctext,article
0,Daman & Diu revokes mandatory Rakshabandhan in...,The Administration of Union Territory Daman an...,The Daman and Diu administration on Wednesday ...,Daman & Diu revokes mandatory Rakshabandhan in...
1,Malaika slams user who trolled her for 'divorc...,Malaika Arora slammed an Instagram user who tr...,"From her special numbers to TV?appearances, Bo...",Malaika slams user who trolled her for 'divorc...
2,'Virgin' now corrected to 'Unmarried' in IGIMS...,The Indira Gandhi Institute of Medical Science...,The Indira Gandhi Institute of Medical Science...,'Virgin' now corrected to 'Unmarried' in IGIMS...
3,Aaj aapne pakad liya: LeT man Dujana before be...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Aaj aapne pakad liya: LeT man Dujana before be...
4,Hotel staff to get training to spot signs of s...,Hotels in Maharashtra will train their staff t...,Hotels in Mumbai and other Indian cities are t...,Hotel staff to get training to spot signs of s...

In [6]:
df = df.drop(columns=["headlines", "ctext"])
df.head(5)

,text,article
0,The Administration of Union Territory Daman an...,Daman & Diu revokes mandatory Rakshabandhan in...
1,Malaika Arora slammed an Instagram user who tr...,Malaika slams user who trolled her for 'divorc...
2,The Indira Gandhi Institute of Medical Science...,'Virgin' now corrected to 'Unmarried' in IGIMS...
3,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Aaj aapne pakad liya: LeT man Dujana before be...
4,Hotels in Maharashtra will train their staff t...,Hotel staff to get training to spot signs of s...

In [18]:
df.loc[df["article"].isna() == True, "article"] = df["text"]

In [19]:
df[df["article"].isna() == True]

Empty DataFrame
Columns: [text, article, x]
Index: []

In [22]:
df.to_csv("data/data.csv", index=False)

In [24]:
d=pd.read_csv("data/data.csv")
d.iloc[0,0]

'The Administration of Union Territory Daman and Diu has revoked its order that made it compulsory for women to tie rakhis to their male colleagues on the occasion of Rakshabandhan on August 7. The administration was forced to withdraw the decision within 24 hours of issuing the circular after it received flak from employees and was slammed on social media.'

In [25]:
d.head()

,text,article,x
0,The Administration of Union Territory Daman an...,Daman & Diu revokes mandatory Rakshabandhan in...,"['daman', 'diu', 'revokes', 'mandatory', 'raks..."
1,Malaika Arora slammed an Instagram user who tr...,Malaika slams user who trolled her for 'divorc...,"['malaika', 'slams', 'user', 'who', 'trolled',..."
2,The Indira Gandhi Institute of Medical Science...,'Virgin' now corrected to 'Unmarried' in IGIMS...,"['virgin', 'now', 'corrected', 'to', 'unmarrie..."
3,Lashkar-e-Taiba's Kashmir commander Abu Dujana...,Aaj aapne pakad liya: LeT man Dujana before be...,"['aaj', 'aapne', 'pakad', 'liya', 'let', 'man'..."
4,Hotels in Maharashtra will train their staff t...,Hotel staff to get training to spot signs of s...,"['hotel', 'staff', 'to', 'get', 'training', 't..."